runtime: python37
default_expiration: '2s'

handlers:
- url: /
  static_files: ajay-main/index.html
  upload: ajay-main/index.html
  expiration: '2s'

- url: /
  static_dir: ajay-main/index.html
  expiration: '2s'
